items:
- name: Docker – dokumentáció
  href: index.md
- name: Első lépések
  items:
  - name: Docker Marketplace-sablon
    href: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/CanonicalandMSOpenTech.DockerOnUbuntuServer1404LTS
  expanded: true
- name: Oktatóanyagok
  items:
  - name: Python-webapp a Docker és a PostgreSQL használatával
    href: ../app-service/containers/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
  - name: CI/CD a Docker Swarm és az Azure DevOps használatával
    href: /azure/container-service/container-service-docker-swarm-mode-setup-ci-cd-acs-engine
  - name: CI/CD a Docker, a Jenkins és a Linux használatával
    href: /azure/virtual-machines/linux/tutorial-jenkins-github-docker-cicd
- name: Útmutatók
  items:
  - name: Docker virtuálisgép-bővítmény
    href: /azure/virtual-machines/linux/dockerextension
  - name: Docker Machine
    href: /azure/virtual-machines/linux/docker-machine
  - name: Docker tárolóregisztrációs adatbázis
    href: /azure/container-registry/container-registry-get-started-portal
- name: További források
  items:
  - name: Azure-ütemterv
    href: https://azure.microsoft.com/roadmap/
  - name: Docker Azure-illesztő
    href: https://docs.docker.com/machine/drivers/azure/
  - name: Docker Azure-hely
    href: https://www.docker.com/docker-azure
  - name: Docker-hely
    href: https://docker.com
ms.openlocfilehash: 79a7bf072be65038000cbcbc17983b4d3b80684f
ms.sourcegitcommit: 7c4fd6fe267f79e760dc9aa8b432caa03d34615d
ms.translationtype: HT
ms.contentlocale: hu-HU
ms.lasthandoff: 09/28/2018
ms.locfileid: "47433769"
