### YamlMime:YamlDocument
ms.openlocfilehash: 9f537ee8fe646a024fb191901b3669b4b5d60d6b
ms.sourcegitcommit: f6e2a03076679d53b550a24828141c4fb978dcf9
ms.translationtype: HT
ms.contentlocale: hu-HU
ms.lasthandoff: 08/27/2018
ms.locfileid: "43086669"
documentType: LandingData
title: Ansible az Azure-ban – Dokumentáció
metadata:
  title: Ansible az Azure-ban – Dokumentáció – Oktatóanyagok, minták, referenciák és forrásanyagok
  description: Megismerheti, hogyan lehet automatizálni az Ansible segítségével a felhőalapú üzembe helyezést, a konfigurációkezelést és az alkalmazások üzembe helyezését.
  ms.service: ansible
  keywords: ansible, azure, devops, oktatóanyagok, minták, referencia
  author: tomarcher
  manager: jeconnoc
  ms.author: tarcher
  ms.topic: landing-page
  ms.date: 08/27/2018
abstract:
  description: Az <a href="http://www.ansible.com">Ansible</a> használatával automatizálható a felhőalapú üzembe helyezés, a konfigurációkezelés és az alkalmazások üzembe helyezése.
sections:
- title: 5 perces gyors útmutatók
  items:
  - type: paragraph
    text: Telepítse az Ansible szoftvert, majd használja Linux rendszerű virtuális gépek létrehozására és kezelésére az Azure-ban.
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Az Ansible telepítése
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Linux rendszerű virtuális gép létrehozása
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Linux rendszerű virtuális gép kezelése
      href: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Részletes útmutatók
  items:
  - type: paragraph
    text: Megtudhatja, hogyan hozhat létre és felügyelhet Azure számítási, hálózatkezelési és tárolási infrastruktúrákat az Ansible használatával.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Linux rendszerű virtuális gép létrehozása, beleértve a virtuális hálózatot, a nyilvános IP-címet és a virtuális hálózati kártyát is.</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Az Ansible futtatása Bash használatával az Azure Cloud Shellben.</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Az Azure-erőforrások dinamikus leltárának létrehozása és kezelése.</a>
    - html: <a href="./ansible-create-configure-vmss">Virtuálisgép-méretezési csoportok létrehozása és kezelése az Azure-ban.</a>
    - html: <a href="./ansible-deploy-app-vmss">Alkalmazások üzembe helyezése virtuálisgép-méretezési csoportokban az Azure-ban.</a>
    - html: <a href="./ansible-create-configure-aks">Azure Kubernetes Service fürtök létrehozása és kezelése.</a>
- title: Referencia
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Forgatókönyv-szerepkörök
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Kiadások és szolgáltatások
      html: <p><a href="./ansible-matrix.md">A modulok és szerepkörök szolgáltatásmátrixa</a></p>
    - title: Eszközök
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Visual Studio Code-bővítmény az Ansible-höz</a></p>
