- name: Ansible az Azure-ban
  href: ./index.yml
- name: Áttekintés
  items:
    - name: Az Ansible az Azure-ban
      href: ./ansible-overview.md
- name: Gyors útmutatók
  expanded: true
  items:
    - name: Az Ansible telepítése és konfigurálása
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Linux rendszerű virtuális gép létrehozása
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
- name: Oktatóanyagok
  items:
    - name: Linux rendszerű teljes virtuális gép létrehozása
      href: /azure/virtual-machines/linux/ansible-create-complete-vm
      maintainContext: true
    - name: Forgatókönyv futtatása a Cloud Shellben
      href: ./ansible-run-playbook-in-cloudshell.md
      maintainContext: true
    - name: Dinamikus leltárak kezelése
      href: ./ansible-manage-azure-dynamic-inventories.md
      maintainContext: true
- name: Referencia
  items:
    - name: Forgatókönyv-szerepkörök
      items:
        - name: azure_module
          href: 'https://galaxy.ansible.com/Azure/azure_modules/'
        - name: azure_preview_module
          href: 'https://galaxy.ansible.com/Azure/azure_preview_modules'
    - name: Kiadások és szolgáltatások
      href: ./ansible-matrix.md
    - name: Azure Container Instances
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_acs_module.html'
    - name: Azure Functions
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html'
    - name: Terheléselosztók
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html'
    - name: Virtual machines (Virtuális gépek)
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html'
    - name: Minden modul az Azure-ban
      href: 'http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure'