- name: A Kubernetes az Azure-on
  href: ./index.yml
- name: Áttekintés
  items:
    - name: A Kubernetes az Azure-on
      href: container-service-intro-kubernetes.md
- name: Gyors útmutatók
  expanded: true
  items:
    - name: A Kubernetes az Azure-on
      href: container-service-kubernetes-walkthrough.md
- name: Oktatóanyagok
  items:
    - name: 1 – Tárolórendszerképek létrehozása
      href: container-service-tutorial-kubernetes-prepare-app.md
    - name: 2 – Tárolóregisztrációs adatbázis létrehozása
      href: container-service-tutorial-kubernetes-prepare-acr.md
    - name: 3 – Kubernetes-fürt létrehozása
      href: container-service-tutorial-kubernetes-deploy-cluster.md
    - name: 4 – Alkalmazás futtatása
      href: container-service-tutorial-kubernetes-deploy-application.md
    - name: 5 – Alkalmazás skálázása
      href: container-service-tutorial-kubernetes-scale.md
    - name: 6 – Alkalmazás frissítése
      href: container-service-tutorial-kubernetes-app-update.md
    - name: 7 – Monitorozás az OMS-szel
      href: container-service-tutorial-kubernetes-monitor.md
- name: Alapelvek
  items:
    - name: Szolgáltatásnév – Kubernetes
      href: container-service-kubernetes-service-principal.md
- name: Útmutatók
  items:
    - name: Kubernetes Windowszal
      href: container-service-kubernetes-windows-walkthrough.md
    - name: Kubernetes webes felület
      href: container-service-kubernetes-ui.md
    - name: Helm-diagramok használata
      href: container-service-kubernetes-helm.md
    - name: A Jenkins használata az ACS-sel
      href: container-service-kubernetes-jenkins.md
    - name: Vázlat használata az ACS-sel
      href: container-service-draft-up.md
    - name: Fürt méretezése
      href: container-service-scale.md
    - name: Figyelés
      items:
        - name: Monitorozás az OMS-szel
          href: container-service-kubernetes-oms.md
        - name: Monitorozás a Datadoggal
          href: container-service-kubernetes-datadog.md
        - name: Monitorozás a Sysdiggel
          href: container-service-kubernetes-sysdig.md
        - name: Monitorozás CoScale-lel
          href: container-service-kubernetes-coscale.md
    - name: Spring Boot-alkalmazások üzembe helyezése
      items:
        - name: Spring Boot-alkalmazás üzembe helyezése Linux rendszeren az Azure Container Service-ben
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Spring Boot-alkalmazás üzembe helyezése Kubernetes-fürtön az Azure Container Service-ben
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: Spring Boot-alkalmazás üzembe helyezése a fabric8 Maven bővítménnyel
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: Referencia
  items:
    - name: Azure CLI
      href: /cli/azure/acs
    - name: REST
      href: /rest/api/container-service
- name: Erőforrások
  items:
    - name: Azure-ütemterv
      href: 'https://azure.microsoft.com/roadmap/'
    - name: GYIK
      href: container-service-faq.md
    - name: Sablonok – ACS Engine
      href: 'https://github.com/Azure/acs-engine'
    - name: Díjszabás
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Régiónkénti elérhetőség
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'http://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Videók
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'