- name: Az Azure AD-szerepkörök dokumentációja
  href: index.yml
- name: Áttekintés
  items:
    - name: Azure AD-szerepkörök
      href: custom-overview.md
- name: Rövid útmutatók
  items:
    - name: Korlátlan számú alkalmazásregisztráció létrehozása
      href: quickstart-app-registration-limits.md
- name: Oktatóanyagok
  items:
    - name: Dinamikus csoport létrehozása
      href: ../enterprise-users/users-revoke-access.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Alapelvek
  expanded: true
  items:
    - name: Azure AD rendszergazdai szerepkörök delegálása
      href: concept-delegation.md
    - name: Alapértelmezett felhasználói engedélyek összehasonlítása
      href: ../fundamentals/users-default-permissions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Az Azure és az Azure AD szerepköreinek összehasonlítása
      href: ../../role-based-access-control/rbac-and-directory-admin-roles.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Az Azure AD felügyeleti egységeinek ismertetése
      href: administrative-units.md
- name: Útmutatók
  expanded: true
  items:
    - name: Felhasználók és szerepkörök
      items:
        - name: Felhasználók hozzárendelése rendszergazdai szerepkörökhöz
          href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Felhasználó jogosultságának visszavonása
          href: ../enterprise-users/users-revoke-access.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Szerepkörök hozzárendelése vendégfelhasználókhoz
          href: ../external-identities/add-guest-to-role.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Vendégfelhasználók hozzáférésének korlátozása
          href: ../enterprise-users/users-restrict-guest-permissions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Dinamikus csoportok és vendégek
          href: ../external-identities/use-dynamic-groups.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Szerepkörök és engedélyek
      expanded: true
      items:
        - name: Szerepkörök és engedélyek
          href: permissions-reference.md
        - name: Szerepkörök megtekintése és hozzárendelése
          href: manage-roles-portal.md
        - name: Saját alkalmazottak delegálása
          href: my-staff-configure.md
    - name: Egyéni szerepkörök
      expanded: true
      items:
        - name: Egyéni szerepkörök áttekintése
          href: custom-overview.md
        - name: Egyéni szerepkör létrehozása
          href: custom-create.md
        - name: Egyéni szerepkör-hozzárendelések megtekintése
          href: custom-view-assignments.md
        - name: Egyéni szerepkörök hozzárendelése az Azure Portalon
          href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Egyéni szerepkörök hozzárendelése a PowerShellben
          href: custom-assign-powershell.md
        - name: Egyéni szerepkörök hozzárendelése vállalati alkalmazásokhoz
          href: custom-enterprise-apps.md
        - name: Egyéni szerepkörengedélyek
          items:
            - name: Alkalmazásregisztráció engedélyei
              href: custom-available-permissions.md
            - name: Nagyvállalati alkalmazás engedélyei
              href: custom-enterprise-app-permissions.md
            - name: Alkalmazás hozzájárulási engedélyei
              href: custom-consent-permissions.md
        - name: Alkalmazás rendszergazdai szerepkörének delegálása
          href: delegate-app-roles.md
    - name: Szerepkörök hozzárendelése csoportokhoz
      items:
        - name: Csoportalapú szerepkör-hozzárendelés előnézete
          href: groups-concept.md
        - name: Szerepkörhöz hozzárendelhető csoport létrehozása
          href: groups-create-eligible.md
        - name: Szerepkörök hozzárendelése csoportokhoz
          href: groups-assign-role.md
        - name: Szerepkör-hozzárendelések eltávolítása csoportokból
          href: groups-remove-assignment.md
        - name: Csoportok szerepkör-hozzárendeléseinek megtekintése
          href: groups-view-assignments.md
        - name: Csoportok jogosulttá tétele szerepkörökre a PIM-ben
          href: groups-pim-eligible.md
        - name: Gyakori kérdések és hibaelhárítás
          href: groups-faq-troubleshooting.md
    - name: A szerepkörök védelme
      items:
        - name: Szerepkör biztonsági tervezése
          href: security-planning.md
        - name: Vészelérési fiókok létrehozása
          href: security-emergency-access.md
    - name: Felügyeleti egységek
      items:
        - name: Felügyeleti egységek áttekintése
          href: administrative-units.md
        - name: Hozzáadás és kezelés
          href: admin-units-manage.md
        - name: Felhasználók hozzáadása és kezelése
          href: admin-units-add-manage-users.md
        - name: Csoportok hozzáadása és kezelése
          href: admin-units-add-manage-groups.md
        - name: Szerepkör hozzárendelése hatókörrel
          href: admin-units-assign-roles.md
        - name: Gyakori kérdések és hibaelhárítás
          href: admin-units-faq-troubleshoot.md
    - name: Hibaelhárítás
      items:
        - name: Támogatás kérése az Azure AD-hez
          href: ../fundamentals/active-directory-troubleshooting-support-howto.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Referencia
  items:
    - name: Legkisebb jogosultságú szerepkörök feladatonként
      href: delegate-by-task.md
    - name: A Microsoft 365-szerepkörök dokumentációja
      href: m365-workload-docs.md
    - name: Graph API
      href: /graph/api/resources/azure-ad-overview?view=graph-rest-1.0
    - name: Azure AD CLI
      href: /cli/azure/ad
    - name: Azure AD PowerShell for Graph
      href: /powershell/azure/active-directory/install-adv2?view=azureadps-2.0
    - name: Azure AD szolgáltatási korlátozások
      href: ../enterprise-users/directory-service-limits-restrictions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context