- name: Az Azure Arc-kompatibilis Kubernetes dokumentációja
  href: index.yml
- name: Áttekintés
  items:
    - name: Az Arc-kompatibilis Kubernetes ismertetése
      href: overview.md
- name: Példák
  items:
    - name: Az Azure Policy beépített elemei
      items:
        - name: Arc-kompatibilis Kubernetes
          href: policy-samples.md
- name: Útmutatók
  items:
    - name: Csatlakozás az Azure Archoz
      items:
        - name: Fürt csatlakoztatása
          href: connect-cluster.md
        - name: Szolgáltatásnév előkészítése
          href: create-onboarding-service-principal.md
    - name: Kezelés
      items:
        - name: Konfigurációk üzembe helyezése GitOps használatával
          href: use-gitops-connected-cluster.md
        - name: Helm-diagramok üzembe helyezése GitOps használatával
          href: use-gitops-with-helm.md
        - name: GitOps kényszerítése az Azure Policyval
          href: use-azure-policy.md
        - name: Monitorozás a tárolókhoz készült Azure Monitor használatával
          href: ../../azure-monitor/insights/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Belépésvezérlési szabályzatok az Azure Policyval
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: IoT-alapú számítási feladatok üzembe helyezése
          href: deploy-azure-iot-edge-workloads.md
    - name: Hibaelhárítás
      href: Troubleshooting.md